/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { FieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnesixKind } from "./fieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnesixKind";
import type { FieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnesixOffsetUnit } from "./fieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnesixOffsetUnit";
import type { FieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnesixOffsetDirection } from "./fieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnesixOffsetDirection";

export type FieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnesix = {
  kind: FieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnesixKind;
  field: string;
  offsetValue?: number;
  offsetUnit?: FieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnesixOffsetUnit;
  offsetDirection?: FieldRegistryEntryDetailsValidatorIrRulesItemOneOfOnesixOffsetDirection;
  message?: string;
};
