/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { FormPhantomFieldValidatorIrRulesItemOneOfOnesixKind } from "./formPhantomFieldValidatorIrRulesItemOneOfOnesixKind";
import type { FormPhantomFieldValidatorIrRulesItemOneOfOnesixOffsetUnit } from "./formPhantomFieldValidatorIrRulesItemOneOfOnesixOffsetUnit";
import type { FormPhantomFieldValidatorIrRulesItemOneOfOnesixOffsetDirection } from "./formPhantomFieldValidatorIrRulesItemOneOfOnesixOffsetDirection";

export type FormPhantomFieldValidatorIrRulesItemOneOfOnesix = {
  kind: FormPhantomFieldValidatorIrRulesItemOneOfOnesixKind;
  field: string;
  offsetValue?: number;
  offsetUnit?: FormPhantomFieldValidatorIrRulesItemOneOfOnesixOffsetUnit;
  offsetDirection?: FormPhantomFieldValidatorIrRulesItemOneOfOnesixOffsetDirection;
  message?: string;
};
