/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { FormFieldValidatorIrRulesItemOneOfOnesixKind } from "./formFieldValidatorIrRulesItemOneOfOnesixKind";
import type { FormFieldValidatorIrRulesItemOneOfOnesixOffsetUnit } from "./formFieldValidatorIrRulesItemOneOfOnesixOffsetUnit";
import type { FormFieldValidatorIrRulesItemOneOfOnesixOffsetDirection } from "./formFieldValidatorIrRulesItemOneOfOnesixOffsetDirection";

export type FormFieldValidatorIrRulesItemOneOfOnesix = {
  kind: FormFieldValidatorIrRulesItemOneOfOnesixKind;
  field: string;
  offsetValue?: number;
  offsetUnit?: FormFieldValidatorIrRulesItemOneOfOnesixOffsetUnit;
  offsetDirection?: FormFieldValidatorIrRulesItemOneOfOnesixOffsetDirection;
  message?: string;
};
