/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { RegisterFieldDtoValidatorIrRulesItemOneOfOnesixKind } from "./registerFieldDtoValidatorIrRulesItemOneOfOnesixKind";
import type { RegisterFieldDtoValidatorIrRulesItemOneOfOnesixOffsetUnit } from "./registerFieldDtoValidatorIrRulesItemOneOfOnesixOffsetUnit";
import type { RegisterFieldDtoValidatorIrRulesItemOneOfOnesixOffsetDirection } from "./registerFieldDtoValidatorIrRulesItemOneOfOnesixOffsetDirection";

export type RegisterFieldDtoValidatorIrRulesItemOneOfOnesix = {
  kind: RegisterFieldDtoValidatorIrRulesItemOneOfOnesixKind;
  field: string;
  offsetValue?: number;
  offsetUnit?: RegisterFieldDtoValidatorIrRulesItemOneOfOnesixOffsetUnit;
  offsetDirection?: RegisterFieldDtoValidatorIrRulesItemOneOfOnesixOffsetDirection;
  message?: string;
};
