/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { UpdateFieldDtoValidatorIrRulesItemOneOfOnesixKind } from "./updateFieldDtoValidatorIrRulesItemOneOfOnesixKind";
import type { UpdateFieldDtoValidatorIrRulesItemOneOfOnesixOffsetUnit } from "./updateFieldDtoValidatorIrRulesItemOneOfOnesixOffsetUnit";
import type { UpdateFieldDtoValidatorIrRulesItemOneOfOnesixOffsetDirection } from "./updateFieldDtoValidatorIrRulesItemOneOfOnesixOffsetDirection";

export type UpdateFieldDtoValidatorIrRulesItemOneOfOnesix = {
  kind: UpdateFieldDtoValidatorIrRulesItemOneOfOnesixKind;
  field: string;
  offsetValue?: number;
  offsetUnit?: UpdateFieldDtoValidatorIrRulesItemOneOfOnesixOffsetUnit;
  offsetDirection?: UpdateFieldDtoValidatorIrRulesItemOneOfOnesixOffsetDirection;
  message?: string;
};
